# derived from: https://github.com/azerothcore/azerothcore-wotlk/blob/master/docker-compose.yml

version: "3"
services:
  db:
    image: mysql:5.7.41
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_USER=trinity
      - MYSQL_PASSWORD=trinity
      - MYSQL_ROOT_PASSWORD=trinity
    volumes:
      - ./env/db:/var/lib/mysql
      - ./env/dbinit:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=trinity --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 40
  worldserver:
    stdin_open: true
    tty: true
    build:
      context: core/
    restart: unless-stopped
    ports:
      - 127.0.0.1:8082:8082
      - 127.0.0.1:8085:8085
      - 127.0.0.1:8086:8086
      - 127.0.0.1:3443:3443
      - 127.0.0.1:7878:7878
    environment:
      - LD_LIBRARY_PATH=/usr/local/mysql/lib
    volumes:
      - ./env/etc:/usr/local/etc
      - ./env/logs:/usr/local/logs
      - ./env/cameras:/usr/local/bin/cameras
      - ./env/dbc:/usr/local/bin/dbc
      - ./env/maps:/usr/local/bin/maps
      - ./env/vmaps:/usr/local/bin/vmaps
      - ./env/mmaps:/usr/local/bin/mmaps
      - ./env/gt:/usr/local/bin/gt
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    working_dir: /usr/local/bin
    command: worldserver
    depends_on:
      db:
        condition: service_healthy
  bnetserver:
    stdin_open: true
    tty: true
    build:
      context: core/
    restart: unless-stopped
    ports:
      - 127.0.0.1:1119:1119
      - 127.0.0.1:8081:8081
    environment:
      - LD_LIBRARY_PATH=/usr/local/mysql/lib
    volumes:
      - ./env/etc:/usr/local/etc
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    working_dir: /usr/local/bin
    command: bnetserver
    depends_on:
      db:
        condition: service_healthy
