#!/bin/sh
set -ex

test -f .extracted.mapextractor || rm -rf maps
test -f .extracted.mapextractor || rm -rf cameras
test -f .extracted.mapextractor || rm -rf dbc
test -f .extracted.mapextractor || mapextractor
touch   .extracted.mapextractor

test -f .extracted.vmap4 || rm -rf vmaps
test -f .extracted.vmap4 || vmap4extractor
test -f .extracted.vmap4 || vmap4assembler
test -f .extracted.vmap4 || rm -rf Buildings
touch   .extracted.vmap4

test -f .extracted.mmaps_generator || rm -rf mmaps
test -f .extracted.mmaps_generator || mmaps_generator
touch   .extracted.mmaps_generator
