#!/bin/sh
set -ex
apt-get update -yq
apt-get install -yq libatomic1 libreadline7 libboost-system1.65.1 libboost-filesystem1.65.1 libboost-program-options1.65.1 libboost-iostreams1.65.1 libboost-thread1.65.1
rm -rf /var/lib/apt/lists/*
